#!/bin/sh

CONFIG=/etc/hexabus_msg_bridge.conf

# wait until we have a routable address on usb0
while ! (ip -o -6 address show usb0 | grep -v "inet6 fe80::") >/dev/null 2>&1
do
	sleep 1
done

if [ -f $CONFIG ]
then
	exec setuidgid hexabus hexabus_msg_bridge -c $CONFIG -L usb0 -L eth0 2>&1
else
	# wait for it to come into existence
	until [ -f $CONFIG ]
	do
		sleep 1
	done
fi
