#!/bin/sh

IFACE=usb0
CONFIG=/etc/hexabus_msg_bridge.conf

if [ -f $CONFIG ]
then
	exec setuidgid hexabus hexabus_msg_bridge -c $CONFIG -L $IFACE 2>&1
else
	# wait for it to come into existence
	until [ -f $CONFIG ]
	do
		sleep 1
	done
fi
