#!/bin/sh

cd ~hexanode
# find one local IPv4 address
# we will simply assume that only one IPv4 address is configured
addr=`ip -o -f inet address show | grep eth0 | awk '{print $4}' | head -n1`

port=80
uid=hexanode 

export server=`dirname $addr`
export port
export uid
exec js node_modules/hexanode-webfrontend/app.js 2>&1
