#!/bin/sh

cd ~hexanode
# find one local IPv4 address
# we will simply assume that only one IPv4 address is configured
addr=`ip -o -f inet address show | grep eth0 | awk '{print $4}' | head -n1`
addr=`dirname $addr`
exec setuidgid hexanode env server=$addr port=3000 npm start hexanode-webfrontend
