# - Try to find libnl3
#
# Once done this will define
#
#  LIBNL_FOUND
#  LIBNL_INCLUDE_DIR
#  LIBNL_LIBRARIES
#  LIBNL_DEFINITIONS

IF (LIBNL_INCLUDE_DIR AND LIBNL_LIBRARY)
	SET(libnl_FIND_QUIETLY TRUE)
ENDIF (LIBNL_INCLUDE_DIR AND LIBNL_LIBRARY)

FIND_PACKAGE(PkgConfig QUIET)
PKG_CHECK_MODULES(PC_LIBNL QUIET libnl-3.0)
SET(LIBNL_DEFINITIONS ${PC_LIBNL_CFLAGS_OTHER})
SET(LIBNL_VERSION_STRING ${PC_LIBNL_VERSION})

FIND_PATH(LIBNL_INCLUDE_DIR netlink/netlink.h
	HINTS ${PC_LIBNL_INCLUDEDIR} ${PC_LIBNL_INCLUDE_DIRS})

FIND_LIBRARY(LIBNL_LIBRARY NAMES nl-3
	HINTS ${PC_LIBNL_LIBDIR} ${PC_LIBNL_LIBRARY_DIRS})

MARK_AS_ADVANCED(LIBNL_INCLUDE_DIR LIBNL_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(libnl
	REQUIRED_VARS LIBNL_LIBRARY LIBNL_INCLUDE_DIR
	VERSION_VAR LIBNL_VERSION_STRING)

IF(LIBNL_FOUND)
	SET(LIBNL_LIBRARIES    ${LIBNL_LIBRARY})
	SET(LIBNL_INCLUDE_DIRS ${LIBNL_INCLUDE_DIR})
ENDIF()
