# - Try to find libnl3-genl
#
# Once done this will define
#
#  LIBGENL_FOUND
#  LIBGENL_INCLUDE_DIR
#  LIBGENL_LIBRARIES
#  LIBGENL_DEFINITIONS

IF (LIBGENL_INCLUDE_DIR AND LIBGENL_LIBRARY)
	SET(libgenl_FIND_QUIETLY TRUE)
ENDIF (LIBGENL_INCLUDE_DIR AND LIBGENL_LIBRARY)

FIND_PACKAGE(PkgConfig QUIET)
PKG_CHECK_MODULES(PC_LIBGENL QUIET libnl-genl-3.0)
SET(LIBGENL_DEFINITIONS ${PC_LIBGENL_CFLAGS_OTHER})
SET(LIBGENL_VERSION_STRING ${PC_LIBGENL_VERSION})

FIND_PATH(LIBGENL_INCLUDE_DIR netlink/genl/genl.h
	HINTS ${PC_LIBGENL_INCLUDEDIR} ${PC_LIBGENL_INCLUDE_DIRS})

FIND_LIBRARY(LIBGENL_LIBRARY NAMES nl-genl-3
	HINTS ${PC_LIBGENL_LIBDIR} ${PC_LIBGENL_LIBRARY_DIRS})

MARK_AS_ADVANCED(LIBGENL_INCLUDE_DIR LIBGENL_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(libgenl
	REQUIRED_VARS LIBGENL_LIBRARY LIBGENL_INCLUDE_DIR
	VERSION_VAR LIBGENL_VERSION_STRING)

IF(LIBGENL_FOUND)
	SET(LIBGENL_LIBRARIES    ${LIBGENL_LIBRARY})
	SET(LIBGENL_INCLUDE_DIRS ${LIBGENL_INCLUDE_DIR})
ENDIF()
