#!/bin/sh

set -e

mkdir -p /home/hexanode/state_machines/build/
mkdir -p /home/hexanode/data/
chown -R hexanode:hexanode /home/hexanode/*

svc -u /etc/service/hexanode-webfrontend
svc -u /etc/service/hexanode-hexajuice

