#!/bin/sh

set -e

if ! id hexanode >/dev/null 2>&1
then
	useradd -r -m hexanode
fi

#su -c 'cd ~; npm install /usr/share/hexanode_webfrontend/hexanode-webfrontend-0.0.1.tgz' hexanode
chown -R hexanode:hexanode /home/hexanode/*
svc -d /etc/service/hexanode-webfrontend
svc -u /etc/service/hexanode-webfrontend
