#ifndef ENDPOINTS_H_

#define EP_DEVICE_DESCRIPTOR     0UL
#define EP_POWER_SWITCH          1UL
#define EP_POWER_METER           2UL
#define EP_TEMPERATURE           3UL
#define EP_BUTTON                4UL
#define EP_HUMIDITY              5UL
#define EP_PRESSURE              6UL
#define EP_ENERGY_METER_TOTAL    7UL
#define EP_ENERGY_METER          8UL
#define EP_SM_CONTROL            9UL
#define EP_SM_UP_RECEIVER        10UL
#define EP_SM_UP_ACKNAK          11UL
#define EP_SM_RESET_ID           12UL
#define EP_HALLSENSOR            21UL
#define EP_ANALOGREAD            22UL
#define EP_SHUTTER               23UL
#define EP_HEXAPUSH_PRESSED      24UL
#define EP_HEXAPUSH_CLICKED      25UL
#define EP_PRESENCE_DETECTOR     26UL
#define EP_HEXONOFF_SET          27UL
#define EP_HEXONOFF_TOGGLE       28UL
#define EP_LIGHTSENSOR           29UL
#define EP_IR_RECEIVER           30UL
#define EP_LIVENESS              31UL
#define EP_GENERIC_DIAL_0        33UL
#define EP_GENERIC_DIAL_1        34UL
#define EP_GENERIC_DIAL_2        35UL
#define EP_GENERIC_DIAL_3        36UL
#define EP_GENERIC_DIAL_4        37UL
#define EP_GENERIC_DIAL_5        38UL
#define EP_GENERIC_DIAL_6        39UL
#define EP_GENERIC_DIAL_7        40UL
#define EP_PV_PRODUCTION         41UL
#define EP_POWER_BALANCE         42UL
#define EP_BATTERY_BALANCE       43UL

#endif // ENDPOINTS_H_
