#!/bin/sh -e

if [ -e /etc/radvd.conf ]
then
	echo "Networks already configured"
	exit 1
fi

python3 /usr/lib/net-choose/net-choose.py eth0 usb0

/etc/init.d/networking restart
/etc/init.d/radvd restart
/etc/init.d/mrd6 restart
